--- 
- name: "Run tasks only if the distribution is Alpine Linux"
  hosts: localhost
  gather_facts: true  # Ensure facts are gathered
  tasks:
    - name: "Check if the distribution is Alpine"
      ansible.builtin.debug:
        var: ansible_facts
    
    - name: "Check if the distribution is Alpine"
      ansible.builtin.debug:
        msg: "This system is running Alpine Linux!"
      when: ansible_facts['distribution'] == "Alpine"

    - name: "Install package only on Alpine"
      ansible.builtin.package:
        name: "curl"
        state: present
      when: ansible_facts['ansible_distribution'] == "Alpine"

    - name: "Create a test file only on Alpine"
      ansible.builtin.file:
        path: "/tmp/alpine_test_file"
        state: touch
      when: ansible_facts['distribution'] == "Alpine"

    - name: "Print a message if running on Alpine"
      ansible.builtin.debug:
        msg: "Alpine-specific tasks have been executed!"
      when: ansible_facts['distribution'] == "Alpine"
